---
- name: Install mailutils
  apt:
    name: mailutils 
    state: latest
    update_cache: yes

- name: Create the file /var/log/update_script.log
  file:
    path: /var/log/update_script.log
    state: touch

- name: Scripts
  include: scripts.yml 

- name: /etc/crontab
  include: crontab.yml
...