---
- name: Install git
  apt:
    name: git 
    state: latest
    update_cache: yes

- name: Clone git repository
  git:
    repo: "{{ git_repository }}"
    dest: /var/www/html/mon-site
    force: yes
...