---
- name: Stock the value of the variable ansible_port
  set_fact:
    configured_port: "{{ ansible_port }}"

- name: Check if we're using the default SSH port
  wait_for:
    port: "22"
    state: "started"
    host: "{{ ansible_host }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: default_ssh

- name: Set inventory ansible_port to 22
  set_fact:
    ansible_port: "22"
  when: default_ssh is defined and default_ssh.state is defined and default_ssh.state == "started"

- name: Run deferred setup to gather facts
  setup:
...
